### PR TITLE
fix: make shallow copy of fastify options before mutations

### LINKED ISSUE #5702: fastify@5.0.0: 'FST_ERR_LOG_INVALID_LOGGER_CONFIG' when no log config is provided (works ok in fastify@4.28.1)
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

N/A

### Node.js version

20.17.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

Creating a fastify instance twice in a row (during testing)  results in:  'FST_ERR_LOG_INVALID_LOGGER_CONFIG' while both times no logger config is provided. The bug does not trigger if only one instance is created.
The error occurs in fastify@5.0.0 but works fine with fastify@4.28.1.

### Link to code that reproduces the bug

https://gist.github.com/seriousme/a1456b1c0432d1029561025c6bdc4095

### Expected Behavior

No error, just as I do not get an error in fastify@4.28.1

### PR DESCRIPTION
**Pull request by dorgelesnzi**
Fix #5702

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: fastify.js [hunk 1]
```diff
@@ -103,6 +103,9 @@ function fastify (options) {
     throw new FST_ERR_OPTIONS_NOT_OBJ()
   }
 
+  // Shallow copy options object to prevent mutations outside of this function
+  options = Object.assign({}, options)
```
Comment (Eomm) [inline fastify.js:107]: I would improve this line too

https://github.com/fastify/fastify/blob/7ddced69c45c294450ab12fe7f92f0d969fe86d7/fastify.js#L100

It can be moved here at 107 and become:

```js
options = options ? { ...options } : {}
```

**Review by gurgunday — APPROVED** [review]

File: fastify.js (hunk 1 above)
Comment (dorgelesnzi) [reply fastify.js:107]: I had first considered this modification but I will skip check on line 102 `typeof options !== 'object'` and will get unexpected behavior when user uses invalid options such as `string`.
But maybe I'm getting the wrong idea ?

**Review by Uzlopak — CHANGES_REQUESTED** [review]
Why not rfdc?

File: test/internals/initialConfig.test.js [hunk 2]
```diff
@@ -367,3 +367,54 @@ test('pluginTimeout should be parsed correctly', t => {
   t.equal(withInvalidTimeout.initialConfig.pluginTimeout, 10000)
   t.end()
 })
+
+test('Should not have issues when using same options object for multiple Fastify instance', async t => {
```
Comment (jsumners) [inline test/internals/initialConfig.test.js:371]: I don't understand how this test proves the PR does what it is supposed to do.

File: fastify.js (hunk 1 above)
Comment (seriousme) [reply fastify.js:107]: fyi: I used [structuredClone() ](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) as a workaround while this PR is finalized.

**Comment by dorgelesnzi** [comment]
> Why not rfdc?

@Uzlopak I can make a deep clone if you find it applicable for issue #5702.
Let me know and I will update my PR ASAP.
Thanks

File: test/internals/initialConfig.test.js (hunk 2 above)
Comment (dorgelesnzi) [reply test/internals/initialConfig.test.js:371]: I use 2 instances in this test in order to check if there is an error.
Thanks to @seriousme from #5702.

Comment (metcoder95) [reply test/internals/initialConfig.test.js:371]: Why not just test that the object passed is not mutated?

**Comment by dancastillo** [comment]
@dorgelesnzi I think @Uzlopak means why not use [rfdc](https://www.npmjs.com/package/rfdc).
This is already a [dependency](https://github.com/fastify/fastify/blob/main/package.json#L203) for fastify

**Comment by climba03003** [comment]
> Why not rfdc?

We must not use `rfdc` because we may pass in `class instance` which is really good for cloning.
I have not test how well `rfdc` play with `class` but not advised to do deep clone.

File: test/internals/initialConfig.test.js (hunk 2 above)
Comment (dorgelesnzi) [reply test/internals/initialConfig.test.js:371]: > Why not just test that the object passed is not mutated?

Yes, It was so obvious 🥲, thanks.
I will clean this test.

File: fastify.js (hunk 1 above)
Comment (climba03003) [reply fastify.js:107]: I don't think structuredClone handle class?
```js
function Instance() {
  this.hello = 'world'
  let hidden = ''
  this.setHidden = (some) => {
    hidden = some
  }
  this.getHidden = () => hidden
}
var a = { instance: new Instance() }
var b = structuredClone(a) // Error
```

**Review by metcoder95 — APPROVED** [review]

File: fastify.js (hunk 1 above)
Comment (Eomm) [reply fastify.js:107]: > But maybe I'm getting the wrong idea ?


```js
function fastify (options) {
  // Options validations
  if (options && typeof options !== 'object') {
    throw new FST_ERR_OPTIONS_NOT_OBJ()
  } else {
    // Shallow copy options object to prevent mutations outside of this function
    options = Object.assign({}, options)
  }

  if (options.querystringParser && typeof options.querystringParser !== 'function') {
 ....
```

**Comment by dorgelesnzi** [comment]
@Eomm Can you please review the updated code ? Thanks !

File: fastify.js [hunk 3]
```diff
@@ -97,12 +97,13 @@ function defaultBuildPrettyMeta (route) {
...
   // Options validations
-  options = options || {}
-
-  if (typeof options !== 'object') {
+  if (options && typeof options !== 'object') {
     throw new FST_ERR_OPTIONS_NOT_OBJ()
   }
 
+  // Shallow copy options object to prevent mutations outside of this function
+  options = Object.assign({}, options)
```
Comment (Eomm) [inline fastify.js:105]:
```suggestion
  } else {
    // Shallow copy options object to prevent mutations outside of this function
    options = Object.assign({}, options)
  }
```

**Review by Eomm — CHANGES_REQUESTED** [review]
The else is important

**Review by gurgunday — APPROVED** [review]
Lgtm

**Comment by dorgelesnzi** [comment]
@Eomm Can you please review the updated code ? Thanks !

**Review by Eomm — APPROVED** [review]
