### PR TITLE
Better onClose tests and updated avvio to 2.1.1.

### LINKED ISSUE #243: An in-range update of avvio is breaking the build 🚨
## Version **2.1.0** of [avvio](https://github.com/mcollina/avvio) just got published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/fastify/fastify/compare/greenkeeper%2Favvio-2.1.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      avvio
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      2.0.4
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

avvio is a direct dependency of this project **this is very likely breaking your project right now**. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority. I’m sure you can resolve this :muscle:

<details>
<summary>Status Details</summary>

- ❌ **coverage/coveralls** Coverage pending from Coveralls.io [Details](https://coveralls.io/builds/13323486)
- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/fastify/fastify/builds/277012379?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v2.1.0</strong>

<ul>
<li>Updated encapsulation handling for <code>ready</code>, <code>after</code>, <code>onClose</code>, <code>close</code> when a server is given to avvio - <a href="https://urls.greenkeeper.io/mcollina/avvio/pull/23" class="issue-link js-issue-link" data-url="https://github.com/mcollina/avvio/issues/23" data-id="258476822" data-error-text="Failed to load issue title" data-permission-text="Issue title is private">#23</a></li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 11 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/28e0d460716a15a2b89cd495a79ee65fff5cc3db"><code>28e0d46</code></a> <code>Bumped v2.1.0</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/49c88737127f067bbb3c1df5b1a6fec7dd261ac3"><code>49c8873</code></a> <code>Merge pull request #23 from mcollina/ready-close-context</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/f1b6860c3a5d5d153804530fee5c35f26edfeb33"><code>f1b6860</code></a> <code>Updated docs</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/99b87af44fd389d2aa43ba753ed28c358c966e43"><code>99b87af</code></a> <code>Updated function signature</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/f6b6ec9be9a5a1b3dbd962714b792ede8aca48e2"><code>f6b6ec9</code></a> <code>Updated docs</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/3314f8439f32a32db04d589d52cc5f94bbe8b9a1"><code>3314f84</code></a> <code>Updated test</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/a1c88268e7c4a3e6d03a0c0f9b0036c3eb08cb19"><code>a1c8826</code></a> <code>Provide encapsulation only if initialized with a server</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/a87421e03388f6af791406d775c9c5328b17b40d"><code>a87421e</code></a> <code>Updated encapsulate functions</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/ca9ada9803feb09105e8c8ba390ba305966a82f0"><code>ca9ada9</code></a> <code>Updated test</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/77a1244843c572968d9db14c3dcaeb7211ce77cc"><code>77a1244</code></a> <code>Updated encapsulation handling</code></li>
<li><a href="https://urls.greenkeeper.io/mcollina/avvio/commit/968eedbcc140bcc7f7e49f3de5754c7b23ec77d2"><code>968eedb</code></a> <code>Updated .gitignore</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/mcollina/avvio/compare/7549f8a779e34f10364d34f1c0b9bd76a07bda7a...28e0d460716a15a2b89cd495a79ee65fff5cc3db">full diff</a></p>
</details>

<details>
<summary>Not sure how things should work exactly?</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html) and of course you may always [ask my humans](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #243 
Fixes https://github.com/fastify/fastify/issues/237

### CODE REVIEW

File: fastify.js [hunk 1]
```diff
@@ -237,17 +237,17 @@ function build (options) {
...
 
-    const middlewares = Object.assign([], instance._middlewares)
-    instance = Object.create(instance)
+    const middlewares = Object.assign([], old._middlewares)
+    const instance = Object.create(old)
     instance._Reply = Reply.buildReply(instance._Reply)
     instance._Request = Request.buildRequest(instance._Request)
     instance._contentTypeParser = ContentTypeParser.buildContentTypeParser(instance._contentTypeParser)
-    instance._hooks = Hooks.buildHooks(instance._hooks)
+    instance._hooks = Hooks.buildHooks(instance._hooks, instance)
```
Comment (delvedor) [inline fastify.js]: `instance` is not more needed, as well as [`._fastify`](https://github.com/fastify/fastify/blob/ac1eec2bf60357a88d7e17ba577d7fde58db784f/lib/hooks.js#L14) inside `hooks.js`

Comment (mcollina) [reply fastify.js]: done
