### PR TITLE
fix: onRoute hook should not be called when it registered after route

### LINKED ISSUE #4044: onRoute hook executed for endpoint declared before registering it
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Plugin version

_No response_

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

When the `onRoute` hook is registered after a GET handler, it is executed for the HEAD route only.

### Steps to Reproduce

```
const fastify = require('fastify')
const app = fastify()

app.addHook('onRoute', function inspector(routeOptions) {
  console.log('before ' + routeOptions.method)
})

app.get('/', function (request, reply) { })

app.addHook('onRoute', function inspector(routeOptions) {
  console.log('after ' + routeOptions.method)
})

app.ready()
```

Prints:

```
before GET
before HEAD
after HEAD
```

### Expected Behavior

I think the after hook should not be executed.

It should print:

```
before GET
before HEAD
```

### PR DESCRIPTION
**Pull request by climba03003**
Fixes #4044 

I don't think we should fix #4044, but I submit this PR for others to determine. 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you send the refactoring into its own PR? After merging that, this would be simpler to review

**Comment by mcollina** [comment]
can you rebase?

File: lib/route.js [hunk 1]
```diff
@@ -320,19 +328,21 @@ function buildRouting (options) {
...
+      const { exposeHeadRoute } = opts
+      const hasRouteExposeHeadRouteFlag = exposeHeadRoute != null
+      const shouldExposeHead = hasRouteExposeHeadRouteFlag ? exposeHeadRoute : globalExposeHeadRoutes
+
+      if (shouldExposeHead && options.method === 'GET' && !hasHEADHandler) {
+        const onSendHandlers = parseHeadOnSendHandlers(opts.onSend)
+        prepareRoute.call(this, { method: 'HEAD', url: path, options: { ...opts, onSend: onSendHandlers }, isFastify: true })
+      } else if (hasHEADHandler && exposeHeadRoute) {
+        warning.emit('FSTDEP007')
+      }
```
Comment (mcollina) [inline lib/route.js:345]: Could we just do this and keep emitting `onRoute` for `HEAD` routes too?

Comment (climba03003) [reply lib/route.js:345]: No, we need to remove the `fastify` one when it is needed otherwise the user is force to added `HEAD` route before `GET` route.

Comment (mcollina) [reply lib/route.js:345]: > No, we need to remove the fastify one when it is needed otherwise user is force to add the HEAD route before GET route.

I thought this was already the case. I had to fix quite a few regressions due to this.

Comment (climba03003) [reply lib/route.js:345]: > I thought this was already the case.

Actually, no. It is force to create route in sync, but not restricted the order.

For example, 
```js
import Fastify from 'fastify'

{
  // order is not restricted
  const fastify = Fastify()
  
  fastify.get('/', async () => '')
  fastify.head('/', async () => '') // it works
}

{
  // order is not restricted
  const fastify = Fastify()
  
  fastify.get('/', async () => '')
  fastify.after(() => {
    fastify.head('/', async () => '') // it just ignored without any warning.
  })
}
```

**Review by RafaelGSS — COMMENTED** [review]
I concur with @climba03003 that it doesn't need to be strictly synced. Also, it might be a breaking change.

**Comment by climba03003** [comment]
> They will be affected, won't they?

I don't think it will be affected. Or you can describe more on what is the expected behavior you would like to see.

**Review by Eomm — APPROVED** [review]
> They can be aware this route is generate by fastify.

I think this is not useful for the user.

In this case we are saying that the hook is executed more times than the expected

**Comment by Eomm** [comment]
Yes, it is.
It was wrong that we were not throwing

> exposeHeadRoute: creates a sibling HEAD route for any GET routes. Defaults to the value of [exposeHeadRoutes](https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#exposeHeadRoutes) instance option. If you want a custom HEAD handler without disabling this option, **make sure to define it before the GET route.**


from: https://github.com/fastify/fastify/blob/main/docs/Reference/Routes.md
