### PR TITLE
enforce utf8 as default charset

### LINKED ISSUE #913: Use UTF8 as default charset for Text and JSON
Hi, when I return a string like `ÄÜÖ` the browser is interpreted as
```
Ã„ÃœÃ–
```
fastify will respond with
```
content-type: text/html;
content-type: application/json;
```
it's obvious that I use the wrong charset but UTF8 is defacto standard and should be used as default.
```
content-type: text/html; charset=utf-8
content-type: application/json; charset=utf-8
```

> A Unicode encoding such as UTF-8 is a good choice for a number of [reasons](https://www.w3.org/International/questions/qa-choosing-encodings).

References:
* https://www.w3.org/International/questions/qa-choosing-encodings
* https://www.w3.org/International/articles/http-charset/index#charset

### PR DESCRIPTION
**Pull request by StarpTech**
Fix #913 

I updated all docs to promote good practice.

This should be handled as minor change. The charset of JSON is `utf8`. The default charset of `text` isn't given but we can protect users against crazy misinterpretations. `utf8` [is widely adopted](https://w3techs.com/technologies/overview/character_encoding/all) and defacto standard and most supported charset.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/reply.js [hunk 1]
```diff
@@ -51,28 +51,28 @@ Reply.prototype.send = function (payload) {
   }
 
   var contentType = getHeader(this, 'content-type')
-  var contentTypeNotSet = contentType === undefined
+  var hasContentType = contentType !== undefined
```
Comment (StarpTech) [inline lib/reply.js]: I change the name to be more expressive `has*` instead `*NotSet`

**Comment by jsumners** [comment]
I think a case could be made that this is a major change. Except, `application/json` is supposed to be UTF-8 by specification. So it could be a bug fix.

**Comment by StarpTech** [comment]
Due to the fact, that a receiver could have a different default charset as utf8 we should handle it as minor change and enforce this best practice to have a predictable behavior.

**Comment by StarpTech** [comment]
@mcollina did you noticed https://github.com/shieldfy/API-Security-Checklist/issues/25 ? Why don't cover it for free when we don't break things?

**Comment by jsumners** [comment]
@mcollina yes, the spec requires JSON to be UTF-8. But that doesn't mean clients always transfer it as UTF-8 when the character set isn't explicitly set. There isn't any harm in being explicit here.

**Comment by StarpTech** [comment]
> There was some discussion in https://github.com/fastify/fastify/issues/380.

Correct, but read the later comments and read the security vulnerability it's an annoying topic and can be fixed by forcing the default charset.

**Comment by StarpTech** [comment]
@mcollina or here from changelog of express 4.16.0

> Set charset as "UTF-8" for .js and .json

**Comment by StarpTech** [comment]
Many frameowork and browser use `application/json; charset=utf-8` instead `application/json;charset=utf-8` opinions?

**Comment by jsumners** [comment]
They are technically equivalent but the extra space is more legible.
