### PR TITLE
Emit a warning when validating undefined schemas

### LINKED ISSUE #4634: Error: Schema for validaton is undefined
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.15.0

### Plugin version

_No response_

### Node.js version

any

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

4.15 release have a backward compatibility issue ([PR](https://github.com/fastify/fastify/pull/4620)): it throws an error if schema for validation is undefined. 

For example, we get a schemas and pass them to fastify.

```ts
const { headers, body } = getSchemas();

fastify.post('/', {
  schema: {
    headers,
    body
  }
}
```

### Steps to Reproduce

```ts
const fastify = require("fastify")({ logger: true });

fastify.get(
  "/",
  {
    schema: {
      headers: undefined,
    },
  },
  () => {
    return "hello";
  }
);

const start = async () => {
  try {
    await fastify.listen({ port: 3000 });
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
```

Server throws an error `Failed building the validation schema for GET: /, due to error headers schema is undefined"` when started

### Expected Behavior

I think that `undefined` is acceptable value, which means that validation will be skipped.

### PR DESCRIPTION
**Pull request by franher**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Emit `FSTWRN001` warning message on the schema validation.

Fix #4634.

### CODE REVIEW

File: lib/warnings.js [hunk 1]
```diff
@@ -27,4 +27,12 @@ warning.create('FastifyDeprecation', 'FSTDEP013', 'Direct return of "trailers" f
 
 warning.create('FastifyDeprecation', 'FSTDEP014', 'You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.')
 
+warning.create('FastifyDeprecation', 'FSTDEP015', 'The headers schema for the route is undefined. This may indicate the schema is not valid or missing.')
```
Comment (climba03003) [inline lib/warnings.js:30]: Please use a single deprecation warning. You can pass a variable inside the message.

```suggestion
warning.create('FastifyDeprecation', 'FSTDEP015', 'The %s schema for the route is undefined. This may indicate the schema is not valid or missing.')
```

File: lib/validation.js [hunk 2]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
     }
     context[headersSchema] = compile({ schema: headersSchemaLowerCase, method, url, httpPart: 'headers' })
   } else if (Object.hasOwnProperty.call(schema, 'headers')) {
-    throw new Error('headers schema is undefined')
+    warning.emit('FSTDEP015')
```
Comment (climba03003) [inline lib/validation.js:86]:
```suggestion
    warning.emit('FSTDEP015', 'headers')
```

File: lib/validation.js [hunk 3]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
...
   }
 
   if (schema.body) {
     context[bodySchema] = compile({ schema: schema.body, method, url, httpPart: 'body' })
   } else if (Object.hasOwnProperty.call(schema, 'body')) {
-    throw new Error('body schema is undefined')
+    warning.emit('FSTDEP016')
```
Comment (climba03003) [inline lib/validation.js:92]:
```suggestion
    warning.emit('FSTDEP015', 'body')
```

File: lib/validation.js [hunk 4]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
...
   }
 
   if (schema.querystring) {
     context[querystringSchema] = compile({ schema: schema.querystring, method, url, httpPart: 'querystring' })
   } else if (Object.hasOwnProperty.call(schema, 'querystring')) {
-    throw new Error('querystring schema is undefined')
+    warning.emit('FSTDEP017')
```
Comment (climba03003) [inline lib/validation.js:98]:
```suggestion
    warning.emit('FSTDEP015', 'querystring')
```

File: lib/validation.js [hunk 5]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
...
   }
 
   if (schema.params) {
     context[paramsSchema] = compile({ schema: schema.params, method, url, httpPart: 'params' })
   } else if (Object.hasOwnProperty.call(schema, 'params')) {
-    throw new Error('params schema is undefined')
+    warning.emit('FSTDEP018')
```
Comment (climba03003) [inline lib/validation.js:104]:
```suggestion
    warning.emit('FSTDEP015', 'params')
```

File: lib/warnings.js [hunk 6]
```diff
@@ -27,4 +27,12 @@ warning.create('FastifyDeprecation', 'FSTDEP013', 'Direct return of "trailers" f
...
+
+warning.create('FastifyDeprecation', 'FSTDEP016', 'The body schema for the route is undefined. This may indicate the schema is not valid or missing.')
+
+warning.create('FastifyDeprecation', 'FSTDEP017', 'The querystring schema for the route is undefined. This may indicate the schema is not valid or missing.')
+
+warning.create('FastifyDeprecation', 'FSTDEP018', 'The params schema for the route is undefined. This may indicate the schema is not valid or missing.')
```
Comment (climba03003) [inline lib/warnings.js:36]:
```suggestion
```

File: test/schema-feature.test.js [hunk 7]
```diff
@@ -281,61 +276,82 @@ test('Should throw if the schema headers is undefined', t => {
...
+  process.on('warning', onWarning)
+  function onWarning (warning) {
+    t.equal(warning.name, 'FastifyDeprecation')
+    t.equal(warning.code, 'FSTDEP016')
+  }
+
+  t.teardown(() => {
+    process.removeListener('warning', onWarning)
+    warning.emitted.set('FSTDEP016', false)
+  })
```
Comment (climba03003) [inline test/schema-feature.test.js:295]:
```suggestion
  function onWarning (warning) {
    t.equal(warning.name, 'FastifyDeprecation')
    t.equal(warning.code, 'FSTDEP015')
  }

  t.teardown(() => {
    process.removeListener('warning', onWarning)
    warning.emitted.set('FSTDEP015', false)
  })
```

File: test/schema-feature.test.js [hunk 8]
```diff
@@ -281,61 +276,82 @@ test('Should throw if the schema headers is undefined', t => {
...
+  process.on('warning', onWarning)
+  function onWarning (warning) {
+    t.equal(warning.name, 'FastifyDeprecation')
+    t.equal(warning.code, 'FSTDEP017')
+  }
+
+  t.teardown(() => {
+    process.removeListener('warning', onWarning)
+    warning.emitted.set('FSTDEP017', false)
+  })
```
Comment (climba03003) [inline test/schema-feature.test.js:320]:
```suggestion
  function onWarning (warning) {
    t.equal(warning.name, 'FastifyDeprecation')
    t.equal(warning.code, 'FSTDEP015')
  }

  t.teardown(() => {
    process.removeListener('warning', onWarning)
    warning.emitted.set('FSTDEP015', false)
  })
```

File: test/schema-feature.test.js [hunk 9]
```diff
@@ -281,61 +276,82 @@ test('Should throw if the schema headers is undefined', t => {
...
+  process.on('warning', onWarning)
+  function onWarning (warning) {
+    t.equal(warning.name, 'FastifyDeprecation')
+    t.equal(warning.code, 'FSTDEP018')
+  }
+
+  t.teardown(() => {
+    process.removeListener('warning', onWarning)
+    warning.emitted.set('FSTDEP018', false)
+  })
```
Comment (climba03003) [inline test/schema-feature.test.js:345]:
```suggestion
  function onWarning (warning) {
    t.equal(warning.name, 'FastifyDeprecation')
    t.equal(warning.code, 'FSTDEP015')
  }

  t.teardown(() => {
    process.removeListener('warning', onWarning)
    warning.emitted.set('FSTDEP015', false)
  })
```

**Review by climba03003 — CHANGES_REQUESTED** [review]
Please use a single deprecation warning.

**Comment by franher** [comment]
> Please use a single deprecation warning.

I am applying all the suggestions right now. Thank you!

File: lib/validation.js (hunk 5 above)
Comment (franher) [reply lib/validation.js]: resolved with a3094e78abe4a400fb0c6f7f2456d104d62c5d18

File: lib/warnings.js (hunk 6 above)
Comment (franher) [reply lib/warnings.js]: resolved with a3094e78abe4a400fb0c6f7f2456d104d62c5d18

File: test/schema-feature.test.js (hunk 7 above)
Comment (franher) [reply test/schema-feature.test.js]: resolved with a3094e78abe4a400fb0c6f7f2456d104d62c5d18

**Comment by franher** [comment]
All the suggestion has been applied on a3094e78abe4a400fb0c6f7f2456d104d62c5d18.

File: lib/validation.js [hunk 10]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
     }
     context[headersSchema] = compile({ schema: headersSchemaLowerCase, method, url, httpPart: 'headers' })
   } else if (Object.hasOwnProperty.call(schema, 'headers')) {
-    throw new Error('headers schema is undefined')
+    warning.emit('FSTDEP015', 'headers')
```
Comment (Eomm) [inline lib/validation.js:86]: the user does not know the route that triggers it - it would hard to debug without it

(the error was carrying the information)

File: lib/validation.js [hunk 11]
```diff
@@ -13,6 +13,8 @@ const {
   FST_ERR_SCH_RESPONSE_SCHEMA_NOT_NESTED_2XX
 } = require('./errors')
 
+const warning = require('./warnings')
```
Comment (Eomm) [inline lib/validation.js:16]: need a test for it - what if I have 2 routes with undefined schema? does the warning show up once?

In this case I think it should be emitted for every route

Comment (franher) [reply lib/validation.js:16]: Hello @Eomm, it is emitted only once. As far as I see, [process-warning](https://github.com/fastify/process-warning) guarantees that the same warning is emitted only once.

We can't have a warning emitted for every route if we use the same warning code for all the routes. Perhaps, we could emit a warning with a dynamic code every time, but it would imply:

1. Creating the warning directly on `validations.js`.
2. The warning code would be dynamic, so we need to find a way to avoid collisions to emit still the warning for every route with "_undefined_ schema".

Please, note it is the first time I'm working on the Fastify codebase, so please, correct me if I'm wrong or if there is another simpler way than my previous thought.

File: lib/validation.js (hunk 10 above)
Comment (franher) [reply lib/validation.js]: commit with the proposed message: 5f2465a04ead6e8d174837bc3094a13ba762bac7

File: lib/validation.js (hunk 11 above)
Comment (Eomm) [reply lib/validation.js:16]: https://github.com/fastify/process-warning/pull/78 👍🏼 

You will need to add a boolean and bump the module whenever we release it please 🙏🏼

File: lib/validation.js [hunk 12]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
...
   if (schema.querystring) {
     context[querystringSchema] = compile({ schema: schema.querystring, method, url, httpPart: 'querystring' })
   } else if (Object.hasOwnProperty.call(schema, 'querystring')) {
-    throw new Error('querystring schema is undefined')
+    warning.emit('FSTDEP015', 'querystring', method, url)
   }
 
   if (schema.params) {
     context[paramsSchema] = compile({ schema: schema.params, method, url, httpPart: 'params' })
   } else if (Object.hasOwnProperty.call(schema, 'params')) {
```
Comment (metcoder95) [inline lib/validation.js:103]: This statement will also cover situations where the schema part is `null`, for instance not it won't match the sentence given on the deprecation.

wdyt if we extend the deprecation message to make it agnostic, and just indicate that the part is missed? 🤔

File: lib/warnings.js [hunk 13]
```diff
@@ -27,4 +27,6 @@ warning.create('FastifyDeprecation', 'FSTDEP013', 'Direct return of "trailers" f
 
 warning.create('FastifyDeprecation', 'FSTDEP014', 'You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.')
 
+warning.create('FastifyDeprecation', 'FSTDEP015', 'The %s schema for %s: %s is undefined. This may indicate the schema is not well specified.')
```
Comment (metcoder95) [inline lib/warnings.js:30]: Shall we indicate that this behavior will change in `v5`?

File: test/schema-feature.test.js [hunk 14]
```diff
@@ -281,61 +276,82 @@ test('Should throw if the schema headers is undefined', t => {
...
-      querystring: undefined
+      params: undefined
     }
   })
 
-  fastify.ready(err => {
-    t.equal(err.code, 'FST_ERR_SCH_VALIDATION_BUILD')
-    t.equal(err.message, 'Failed building the validation schema for GET: /:id, due to error querystring schema is undefined')
-  })
+  fastify.ready()
```
Comment (metcoder95) [inline test/schema-feature.test.js:354]: `Fastify#ready` returns a Promise 😅

File: lib/validation.js (hunk 12 above)
Comment (franher) [reply lib/validation.js:103]: Good catch! I've changed the message. See the example below. Any feedback is welcome :)
```console
[FSTDEP015] FastifyDeprecation: The params schema for GET: /:id is missed. This may indicate the schema is not well specified.
```

File: lib/warnings.js (hunk 13 above)
Comment (franher) [reply lib/warnings.js]: Will we keep throwing the error (#4620) on `v5`, @Eomm? If yes, then we can modify the warning exception message to something like this:

> The params schema for GET: /:id is missed. This may indicate the schema is not well specified. Ir will cause a runtime error building the validation schema in `fastify@5`.'

WDYT?

File: lib/validation.js (hunk 11 above)
Comment (franher) [reply lib/validation.js:16]: Any news for the new release of the `process-warning`? Thank you

File: test/schema-feature.test.js (hunk 14 above)
Comment (franher) [reply test/schema-feature.test.js:354]: @metcoder95 I have two proposals. What do you think could be better for those specific tests?

1. Call `ready` with a callback
```js
fastify.ready(err => t.error(err))
```

2. Use inject and test the endpoint
```js
  fastify.inject({
    method: 'GET',
    url: '/:id'
  }, (error, res) => {
    t.error(error)
    t.equal(res.statusCode, 200)
  })
```

Thank you!

**Comment by jsumners** [comment]
Is the underlying issue actually a deprecation?

File: lib/validation.js (hunk 11 above)
Comment (Eomm) [reply lib/validation.js:16]: Done: https://github.com/fastify/process-warning/releases/tag/v2.2.0

**Comment by jsumners** [comment]
> > Is the underlying issue actually a deprecation?
> 
> There is no feature to deprecate here - we are just sanitizing the input IMHO

Then this should not be a `FSTDEP` error. And I'm not clear why the log isn't sufficient. I think it would be tremendously more difficult to deal with a process warning than the log.

**Comment by Eomm** [comment]
A warning is always visible and I consider this issue a security threat (a developer thinks to validate the input, but it is not)

File: lib/validation.js (hunk 11 above)
Comment (franher) [reply lib/validation.js:16]: Perfect, I've just updated the code using the new version and the new `unlimited` flag enabled. Note that the validation warning is emitted twice for GET routes, one for the method GET and another for the method HEAD.

> [FSTDEP015] FastifyDeprecation: The body schema for GET: /undefinedBody/:id is missed. This may indicate the schema is not well specified.
[FSTDEP015] FastifyDeprecation: The body schema for HEAD: /undefinedBody/:id is missed. This may indicate the schema is not well specified.

File: test/schema-feature.test.js (hunk 14 above)
Comment (franher) [reply test/schema-feature.test.js]: I've used the second approach.

File: lib/warnings.js (hunk 13 above)
Comment (franher) [reply lib/warnings.js]: Okay, I will keep the current message if this is not an issue. For instance:

> The params schema for GET: /:id is missed. This may indicate the schema is not well specified. It will cause a runtime error building the validation schema in fastify@5.'

**Comment by franher** [comment]
Ready for review again, I have applied all the suggestions. Thank you!

File: lib/warnings.js [hunk 15]
```diff
@@ -27,4 +27,6 @@ warning.create('FastifyDeprecation', 'FSTDEP013', 'Direct return of "trailers" f
 
 warning.create('FastifyDeprecation', 'FSTDEP014', 'You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.')
 
+warning.create('FastifyDeprecation', 'FSTDEP015', 'The %s schema for %s: %s is missed. This may indicate the schema is not well specified.', { unlimited: true })
```
Comment (Eomm) [inline lib/warnings.js:30]:
```suggestion
warning.create('FastifyDeprecation', 'FSTDEP015', 'The %s schema for %s: %s is missing. This may indicate the schema is not well specified.', { unlimited: true })
```

**Review by Eomm — APPROVED** [review]
LGTM - just a suggestion cc @Fdawgs

File: lib/warnings.js [hunk 16]
```diff
@@ -27,4 +27,6 @@ warning.create('FastifyDeprecation', 'FSTDEP013', 'Direct return of "trailers" f
 
 warning.create('FastifyDeprecation', 'FSTDEP014', 'You are trying to set/access the default route. This property is deprecated. Please, use setNotFoundHandler if you want to custom a 404 handler or the wildcard (*) to match all routes.')
 
+warning.create('FastifyDeprecation', 'FSTDEP015', 'The %s schema for %s: %s is missing. This may indicate the schema is not well specified.', { unlimited: true })
```
Comment (jsumners) [inline lib/warnings.js:30]: As stated in https://github.com/fastify/fastify/pull/4647#issuecomment-1496427763, this is not a deprecation. It should not be emitted as such.

Comment (climba03003) [inline lib/warnings.js:30]:
```suggestion
warning.create('FastifyWarning', 'FSTWRN001', 'The %s schema for %s: %s is missing. This may indicate the schema is not well specified.', { unlimited: true })
```

File: lib/validation.js [hunk 17]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
     }
     context[headersSchema] = compile({ schema: headersSchemaLowerCase, method, url, httpPart: 'headers' })
   } else if (Object.hasOwnProperty.call(schema, 'headers')) {
-    throw new Error('headers schema is undefined')
+    warning.emit('FSTDEP015', 'headers', method, url)
```
Comment (climba03003) [inline lib/validation.js:86]:
```suggestion
    warning.emit('FSTWRN001', 'headers', method, url)
```

File: lib/validation.js [hunk 18]
```diff
@@ -81,25 +83,25 @@ function compileSchemasForValidation (context, compile, isCustom) {
...
   } else if (Object.hasOwnProperty.call(schema, 'body')) {
-    throw new Error('body schema is undefined')
+    warning.emit('FSTDEP015', 'body', method, url)
   }
 
   if (schema.querystring) {
     context[querystringSchema] = compile({ schema: schema.querystring, method, url, httpPart: 'querystring' })
   } else if (Object.hasOwnProperty.call(schema, 'querystring')) {
-    throw new Error('querystring schema is undefined')
+    warning.emit('FSTDEP015', 'querystring', method, url)
```
Comment (climba03003) [inline lib/validation.js:98]:
```suggestion
    warning.emit('FSTWRN001', 'querystring', method, url)
```

File: test/schema-feature.test.js [hunk 19]
```diff
@@ -253,88 +254,180 @@ test('Should not change the input schemas', t => {
...
-  t.plan(2)
+test('Should emit warning if the schema params is undefined', t => {
+  t.plan(4)
   const fastify = Fastify()
 
-  fastify.get('/:id', {
+  process.on('warning', onWarning)
+  function onWarning (warning) {
+    t.equal(warning.name, 'FastifyDeprecation')
+    t.equal(warning.code, 'FSTDEP015')
```
Comment (climba03003) [inline test/schema-feature.test.js:357]:
```suggestion
    t.equal(warning.name, 'FastifyWarning')
    t.equal(warning.code, 'FSTWRN001')
```

File: test/schema-feature.test.js [hunk 20]
```diff
@@ -253,88 +254,180 @@ test('Should not change the input schemas', t => {
...
+  }
+
+  t.teardown(() => {
+    process.removeListener('warning', onWarning)
+    warning.emitted.set('FSTDEP015', false)
```
Comment (climba03003) [inline test/schema-feature.test.js:362]:
```suggestion
    warning.emitted.set('FSTWRN001', false)
```

File: test/schema-feature.test.js [hunk 21]
```diff
@@ -253,88 +254,180 @@ test('Should not change the input schemas', t => {
...
-  fastify.get('/:id', {
+  let runs = 0
+  const expectedWarningEmitted = [0, 1, 2, 3]
+  // It emits 4 warnings:
+  // - 2 - GET and HEAD for /undefinedParams/:id
+  // - 2 - GET and HEAD for /undefinedBody/:id
+  // => 3 x 4 assertions = 12 assertions
+  function onWarning (warning) {
+    t.equal(warning.name, 'FastifyDeprecation')
+    t.equal(warning.code, 'FSTDEP015')
```
Comment (climba03003) [inline test/schema-feature.test.js:393]:
```suggestion
    t.equal(warning.name, 'FastifyWarning')
    t.equal(warning.code, 'FSTWRN001')
```

File: test/schema-feature.test.js [hunk 22]
```diff
@@ -253,88 +254,180 @@ test('Should not change the input schemas', t => {
...
+    t.equal(runs++, expectedWarningEmitted.shift())
+  }
+
+  process.on('warning', onWarning)
+  t.teardown(() => {
+    process.removeListener('warning', onWarning)
+    warning.emitted.set('FSTDEP015', false)
```
Comment (climba03003) [inline test/schema-feature.test.js:400]:
```suggestion
    warning.emitted.set('FSTWRN001', false)
```

**Review by climba03003 — CHANGES_REQUESTED** [review]

File: lib/warnings.js (hunk 16 above)
Comment (franher) [reply lib/warnings.js]: Change to be emitted as `FastifyWarning` now.

**Comment by jsumners** [comment]
I'm not blocking this. I haven't researched the underlying issue, but I feel like it could be solved in a better way than a process warning.

**Review by climba03003 — APPROVED** [review]

**Comment by franher** [comment]
> I'm not blocking this. I haven't researched the underlying issue, but I feel like it could be solved in a better way than a process warning.

I understand your point. The underlying issue, IMHO, is an unwanted breaking change introduced on 4.15.0 (see https://github.com/fastify/fastify/pull/4620). It could have been reverted totally or, in this case, the solution applied here: avoid the runtime error but highlight the security threat that the missed schema could suppose.

I'm open to working on a different approach :) Thank you for all the tremendous support you are providing with my first contribution. What a welcome Fastify community you have here 🎉 !

**Review by metcoder95 — APPROVED** [review]
LGTM 👍

**Review by Eomm — COMMENTED** [review]
Merging

CI nevative due `file: test/logger.test.js`
Ref https://github.com/fastify/fastify/pull/4648
