### PR TITLE
fix: server.listen listener is not cleanup properly

### LINKED ISSUE #5519: listen() registers a callback even when listen() fails, calling the callback twice - once when it fails and again if it succeeds in a later call
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

_No response_

### Node.js version

22.2.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11 Pro (10.0.22621.3374)

### Description

When you call fastify.listen() and it fails it will launch the callback with err set correctly
If you catch this error, and try to call listen() again later and it succeeds it will return a callback for the current call but it will also trigger a callback for each of the previous listen() calls.

```
/* common settings */
const host = "0.0.0.0";
const port = 3033;

/* Helper to block the port */
const net = require("net");
server = net.createServer();
server.listen(port, host, function () {
  setTimeout(serverClose, 20000);
});

/* Helper function to free the port */
function serverClose() {
  server.close(() => { })
}

/* MRE starts here */
const fastify = require('fastify')();
function tryToListen() {
  fastify.listen({host: host, port: port}, function(err,address) {
    if(err) {
      console.log((new Date()).toISOString(),"tryToListen.then{}",err.toString());
      setTimeout(tryToListen, 5000);
    } else {
      console.log((new Date()).toISOString(),"tryToListen.else{}");
    }
  });
} 

//Let's fire the code
console.log((new Date()).toISOString(),"tryToListen()");
tryToListen();

// we stop listening
setTimeout(fastify.close, 30000);
```

### Link to code that reproduces the bug

_No response_

### Expected Behavior

The expected behavior is for no callback to be register if the listen() attempt fails such that a later successful listen should only call the current callback and not any of the previous callback functions passed to any listen attempts.

The current behavior is that the function is registered as a success callback even if it fails to listen.

A possible workaround would be to retry connecting with a callback that has no path for when there is no error.

There must be a path in the code that registers the callback as a function to call on successful connection, this path seems to be hit even when the connection fails.

Another option is that this is a documented expected behavior in which case it should be in the documentation.

### PR DESCRIPTION
**Pull request by climba03003**
I don't think we should permit multiple calls to `.listen`, but we should also properly cleanup the listener if `node` currently doesn't.

Fixes #5519 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -238,25 +240,33 @@ function listenPromise (server, listenOptions) {
...
+        this[kState].listening = true
         resolve(logServerAddress.call(this, server, listenOptions.listenTextResolver || defaultResolveServerListeningText))
-      })
-      // we set it afterwards because listen can throw
-      this[kState].listening = true
+      }
+      server.once('listening', listeningEventHandler)
     })
 
+    server.listen(listenOptions)
```
Comment (climba03003) [inline lib/server.js:265]: I believe we are safe here without `try-catch`.
The error should go to the error event handler.

`.listening = true` is place inside `listening` event which guarantee to be listening.

**Review by jsumners — APPROVED** [review]
