### PR TITLE
fix: validate invalid route logLevel at registration

### LINKED ISSUE #6124: Server crashes when using an invalid `logLevel` in route options
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.3.3

### Plugin version

_No response_

### Node.js version

22.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

When defining a route in Fastify with an invalid `logLevel`, the server crashes at runtime without a clear or handled error.

Steps to Reproduce
```js
const fastify = require("fastify")({ logger: true });

fastify.get("/", { logLevel: "invalid" }, async () => "hello world");

fastify.listen({ port: 3000 }, (err) => {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
});
```

Then, a call to `/` causes the server to crash.

### Link to code that reproduces the bug

-

### Expected Behavior

the error should not crash the server ungracefully

### PR DESCRIPTION
**Pull request by maxpetrusenko**
## Description
- validate route/plugin `logLevel` values during route registration
- throw `FST_ERR_ROUTE_LOG_LEVEL_INVALID` instead of failing at request time
- document the new error code and custom log-level behavior
- add regression coverage for invalid route `logLevel`

## Testing
- `node --test test/logger/options.test.js`
- `node --test test/internals/errors.test.js`
- `npm run lint:eslint -- lib/route.js lib/errors.js test/logger/options.test.js test/internals/errors.test.js types/errors.d.ts`
- `npm run lint:markdown -- docs/Reference/Routes.md docs/Reference/Errors.md`

Fixes #6124

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jean-michelet — APPROVED** [review]

**Comment by gurgunday** [comment]
There are conflicts :(

File: lib/route.js [hunk 1]
```diff
@@ -635,6 +637,15 @@ function validateHandlerTimeoutOption (handlerTimeout) {
   }
 }
 
+function validateLogLevelOption (logLevel, method, path, logger) {
+  if (logLevel === undefined || logLevel === '') return
```
Comment (metcoder95) [inline lib/route.js]: `nit`: just to add guardrails for `null`


```suggestion
  if (logLevel == null || logLevel === '') return
```

Comment (maxpetrusenko) [reply lib/route.js]: Fixed in `5b115897`.

Applied the null guard in `lib/route.js`, and added regression coverage in `test/logger/options.test.js` to assert `{ logLevel: null }` is treated as omitted rather than rejected.

**Review by gurgunday — APPROVED** [review]
lgtm

I will be closing the other PRs as it seems like the first active PR about this and others' PRs are incorrect

**Review by metcoder95 — APPROVED** [review]
