### PR TITLE
http2: fix req.hostname not set

### LINKED ISSUE #2112: request.hostname isn't set when using HTTP2
## 🐛 Bug Report

`request.hostname` isn't set when using HTTP2.

## To Reproduce

`index.js`:

```js
module.exports = async function (fastify, opts) {
  fastify.get('/', async (req, r) => r.send(`hostname: ${req.hostname}\n`));
};
module.exports.options = { http2: true };
```

## Expected behavior

Running `fastify start -o index.js` and `curl --http2-prior-knowledge http://localhost:3000` gives:

```
hostname: localhost:3000
```

## Actual behavior

```
hostname: undefined
```

## Your Environment

- *node version*: v13.9.0
- *fastify version*: 2.11.0
- *os*: Windows

### PR DESCRIPTION
**Pull request by mohd-akram**
Fixes #2112

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/route.js [hunk 1]
```diff
@@ -307,7 +307,7 @@ function buildRouting (options) {
 
     req.id = req.headers[requestIdHeader] || genReqId(req)
     req.originalUrl = req.url
-    var hostname = req.headers.host
+    var hostname = req.headers[':authority'] || req.headers.host
```
Comment (mcollina) [inline lib/route.js]: Would you mind to invert those?

```suggestion
    var hostname = req.headers.host || req.headers[':authority']
```
