### PR TITLE
fix: handle web stream payload in HEAD route

### LINKED ISSUE #6371: HEAD route throws `ERR_INVALID_ARG_TYPE` error when GET route sends a Web Stream
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.6.1

### Plugin version

_No response_

### Node.js version

22.18.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

15.6

### Summary
Fastify automatically creates a corresponding `HEAD` route for every `GET` route. However, if the `GET` route handler sends a Web Stream (e.g., a `ReadableStream`), making a request to the `HEAD` route throws a `TypeError`.

### Steps to Reproduce
1. Register a `GET` route that replies with a Web Stream payload (e.g., `new ReadableStream(...)`).
2. Start the Fastify server.
3. Send a `HEAD` request to the same route.
4. The server crashes with the error below.

### Error Details
The following `TypeError` is thrown:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of ReadableStream
    at Function.byteLength (node:buffer:777:11)
    ...
```

### Analysis
This error originates from the `headRouteOnSendHandler` function, specifically at this line:

https://github.com/fastify/fastify/blob/1564559c355b4aa1f00f7371f71f896ebe94f862/lib/head-route.js#L19

This line incorrectly assumes the payload is a Buffer-like type (`string`, `Buffer`, or `ArrayBuffer`, ...) to calculate the `Content-Length`.
Thus `Buffer.byteLength` fails causing the error when the payload is a `ReadableStream`.

### Link to code that reproduces the bug

https://github.com/orionmiz/fastify-repro-web-stream-in-head

### Expected Behavior

**HEAD request to a route whose corresponding GET handler sends a Web Stream should not throw an error.**

- The `headRouteOnSendHandler` should not attempt to calculate the `Content-Length` of a stream payload (e.g., by calling `Buffer.byteLength`).
- Instead, in accordance with the HTTP specification, the `HEAD` response must include the exact same headers (such as `Transfer-Encoding` or `Content-Length`) that would have been sent by the corresponding `GET` request.

### PR DESCRIPTION
**Pull request by orionmiz**
Fixes #6371

#### Checklist

- [x] run `npm run test && npm run benchmark --if-present`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/main/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by metcoder95** [comment]
Error doesn't seem related to the PR changes

**Review by jean-michelet — APPROVED** [review]

**Review by gurgunday — APPROVED** [review]
lgtm

File: lib/head-route.js [hunk 1]
```diff
@@ -16,6 +17,15 @@ function headRouteOnSendHandler (req, reply, payload, done) {
     return
   }
 
+  // node:stream/web
+  if (typeof payload.getReader === 'function') {
+    payload.cancel().catch((err) => {
```
Comment (climba03003) [inline lib/head-route.js]: Can you provide the reason in cancel? The user should knows it is cancelled by fastify and due to the HEAD route.

Comment (orionmiz) [reply lib/head-route.js]: Thanks for the review!
A reason message for the stream cancellation has been added to commit [efcd817](https://github.com/fastify/fastify/pull/6372/commits/efcd817743dd39d6fb17ef2d4ba51e2b79eb0c6d).
Please let me know if any further improvements are needed.
