### PR TITLE
Ts routeschema missing type + testing #1378

### LINKED ISSUE #1378: Fastify Typescript RouteSchema missing headers?: JSONSchema
Hello

Thank you for the great Fastify project. We're moving from Express to Fastify, because of async/await support and schema driven approach.

While using fastify v2 with typescript the following code:

```js
  const endpointsSchemas: fastify.RouteSchema = {
    querystring: '#schema-id-1#',
    headers: '#schema-id-2#',
    response: {
      200: '#schema-id-3#',
    },
  };
```

produces ts error:

```sh
error TS2322: Type '{ querystring: string; headers: string; response: { 200: string; }; }' is not assignable to type 'RouteSchema'.
  Object literal may only specify known properties, and 'headers' does not exist in type 'RouteSchema'.
         headers: '#schema-id-2#',
```

fix seems simple:
instead of https://github.com/fastify/fastify/blob/master/fastify.d.ts#L185
```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

it should be

```js
  interface RouteSchema {
    body?: JSONSchema
    querystring?: JSONSchema
    params?: JSONSchema
    headers?: JSONSchema
    response?: {
      [code: number]: JSONSchema,
      [code: string]: JSONSchema
    }
  }
```

If that is correct I'd be happy to open PR with the fix.

Meanwhile we're using self declared type.

### PR DESCRIPTION
**Pull request by reposandermets**
This PR includes work started on #1380 and adds test. Goal of this PR is discussed in #1378 .

Closes #1378 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: test/types/index.ts [hunk 1]
```diff
@@ -138,27 +138,41 @@ server.addHook('onClose', (instance, done) => {
...
+          type: 'string'
         }
       }
     }
-  },
+  }
+}
+
+const opts: fastify.RouteShorthandOptions<http2.Http2Server, http2.Http2ServerRequest, http2.Http2ServerResponse> = {
+  schema,
```
Comment (reposandermets) [inline test/types/index.ts]: Per ["node": ">=6"](https://github.com/fastify/fastify/blob/master/package.json#L75) ran tests using Node v6.16.0 also. So using shorthand property seems okay in this case. Please let me know if changes are required.

**Comment by delvedor** [comment]
Backported in 577a96ee438183ed325305aab918e67e88c65edd.
