### PR TITLE
fix(async-hooks): mixing async and callback style in preHandler option now returns an error

### LINKED ISSUE #5068: bug: FST_ERR_HOOK_INVALID_ASYNC_HANDLER not thrown
The following code should break:

```
const app = require("fastify")({ logger: !true });

// 🤬 DO NOT MIX ASYNC AND CALLBACK STYLE:
async function wrongHook(request, reply, done) {
  console.log("preHandler");
  done();
}

// FastifyError [Error]: Async function has too many arguments. Async hooks should not use the 'done' argument.
// 🚀 app.addHook("preHandler", wrongHook);

app.get(
  "/",
  {
    preHandler: [
      wrongHook, // does not throw
    ],
  },
  async (request, reply) => {
    return { hello: "world" };
  }
);

app.listen({ port: 3000 });
```

If I uncomment the 🚀 line, it will throw an error as expected.
We should validate the route's hook array

### PR DESCRIPTION
**Pull request by giuliowaitforitdavide**
Closes #5068 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/route.js [hunk 1]
```diff
@@ -268,6 +269,10 @@ function buildRouting (options) {
               if (typeof func !== 'function') {
                 throw new FST_ERR_HOOK_INVALID_HANDLER(hook, Object.prototype.toString.call(func))
               }
+
+              if (func.constructor.name === 'AsyncFunction' && func.length === 3) {
```
Comment (Eomm) [inline lib/route.js:273]: not all hooks have the same parameters:

 'onTimeout' - 3
  'onRequest' - 3
  'preParsing' - 4
  'preValidation' - 3
  'preSerialization' - 4
  'preHandler' - 3
  'onSend' - 4
  'onResponse' - 3
  'onError' - 4
  'onRequestAbort - 2

File: test/hooks-async.test.js [hunk 2]
```diff
@@ -923,3 +923,28 @@ t.test('nested hooks to do not crash on 404', t => {
     t.equal(res.statusCode, 404)
   })
 })
+
+test('Register an hook after a plugin inside a plugin (with preHandler option) should fail if mixing async and callback style', t => {
```
Comment (Eomm) [inline test/hooks-async.test.js:927]:
```suggestion
test('Register an hook as route option should fail if mixing async and callback style', t => {
```

**Review by Eomm — CHANGES_REQUESTED** [review]

File: lib/route.js (hunk 1 above)
Comment (giuliowaitforitdavide) [reply lib/route.js]: Following your suggestion and the check done [here](https://github.com/fastify/fastify/blob/7d97dcdf2643bcfbdcf4850867139db8189b82e2/fastify.js#L612) I came up with a small refactor. Do you think it's worth it or should I revert it?

File: lib/validation.js [hunk 3]
```diff
@@ -217,6 +217,26 @@ function validateAsyncHeaders (validatePromise, context, request) {
...
+  }
+
+  const validateParametersLengthFunction = {
+    onSend: length => !(length === 4),
+    preSerialization: length => !(length === 4),
+    onError: length => !(length === 4),
+    preParsing: length => !(length === 4),
+    onReady: length => !(length !== 0),
+    onListen: length => !(length !== 0),
+    onRequestAbort: length => !(length !== 1)
```
Comment (jsumners) [inline lib/validation.js:232]: Please avoid using negated false. `length => length !== 4` is far easier to read than `length => !(length === 4)`.

Comment (giuliowaitforitdavide) [reply lib/validation.js:232]: My bad, I'm fixing

File: lib/validation.js [hunk 4]
```diff
@@ -217,6 +217,26 @@ function validateAsyncHeaders (validatePromise, context, request) {
...
+    onSend: length => length !== 4,
+    preSerialization: length => length !== 4,
+    onError: length => length !== 4,
+    preParsing: length => length !== 4,
+    onReady: length => length === 0,
+    onListen: length => length === 0,
+    onRequestAbort: length => length === 1
+  }
+
+  const defaultValidator = length => !(length === 3)
```
Comment (jsumners) [inline lib/validation.js:235]:
```suggestion
  const defaultValidator = length => length !== 3
```

**Comment by giuliowaitforitdavide** [comment]
I need your hell: I don't understand why the [pipeline](https://github.com/fastify/fastify/actions/runs/6381041796/job/17316704069#step:5:9098) is failing

**Comment by jsumners** [comment]
> I need your help: I don't understand why the [pipeline](https://github.com/fastify/fastify/actions/runs/6381041796/job/17316704069#step:5:9098) is failing

Review https://github.com/fastify/fastify/actions/runs/6381041796/job/17316704069?pr=5069

File: lib/validation.js [hunk 5]
```diff
@@ -217,6 +217,26 @@ function validateAsyncHeaders (validatePromise, context, request) {
     })
 }
 
+function validateAsyncHooks (name, fn) {
```
Comment (Eomm) [inline lib/validation.js:220]: I would keep the old code.
It may seem ugly, but it is fast and with a low memory footprint

https://backend.cafe/the-secrets-behind-high-performance-with-nodejs#heading-silly-code-is-not-so-silly

**Review by metcoder95 — APPROVED** [review]

**Review by jsumners — APPROVED** [review]

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Uzlopak** [comment]
We actually should consider exporting the information regarding the available hooks(preSerializer, onReady...), their type(application hook or LifecycleHook) and their argument count, and maybe if they have payload.

We had so many times the issue, that we implemented in plugins code which needed this info.

**Comment by Eomm** [comment]
> We had so many times the issue, that we implemented in plugins code which needed this info.

I'm still PRO to this - will open a issue for that
