### PR TITLE
fix: unused shared schema to serializer

### LINKED ISSUE #1491: Using named schema in items field breaks schema validation
## 🐛 Bug Report

Using some named schema as `items` in other schema cause exception when using first schema

## To Reproduce

Add schema with simple item. Then add schema for items array and use first schema `$id` in `items`.
Then use the first schema in some route.

Paste your code here:

```js
const fastify = require('fastify')();

(async () => {
  const name = 'item';
  const item = {type: 'object', properties: {foo: {type: 'string'}}};
  fastify.addSchema({
    $id: `${name}`,
    ...item,
  });
  fastify.addSchema({
    $id: `${name}List`,
    type: 'array',
    items: `${name}#`,
  });
  fastify.get(
    '/',
    {
      schema: {
        response: {
          200: `${name}#`,
        },
      },
    },
    async (req, res) => {
      return {};
    }
  );
  await fastify.ready();
  await fastify.listen(3000);
  console.log('app listens');
})();

```

```
(node:21665) UnhandledPromiseRejectionWarning: Error: schema is invalid: data.items should be object,boolean, data.items should be array, data.items should match some schema in anyOf
at Ajv.validateSchema (/tmp/xxx/node_modules/ajv/lib/ajv.js:177:16)
at Ajv._addSchema (/tmp/xxx/node_modules/ajv/lib/ajv.js:306:10)
at Ajv.addSchema (/tmp/xxx/node_modules/ajv/lib/ajv.js:136:29)
at Object.keys.forEach.key (/tmp/xxx/node_modules/fast-json-stringify/index.js:937:11)
at Array.forEach (<anonymous>)
at isValidSchema (/tmp/xxx/node_modules/fast-json-stringify/index.js:936:33)
at build (/tmp/xxx/node_modules/fast-json-stringify/index.js:39:3)
at getValidatorForStatusCodeSchema (/tmp/xxx/node_modules/fastify/lib/validation.js:13:10)
at /tmp/xxx/node_modules/fastify/lib/validation.js:19:21
at Array.reduce (<anonymous>)
```

## Expected behavior

No exception thrown.

## Your Environment

- *node version*: 11
- *fastify version*: 2.0.0
- *os*: Mac, Linux

### PR DESCRIPTION
**Pull request by Eomm**
Closes #1491 

This fix needs to be backported to v1.x

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/schemas.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ Schemas.prototype.resolve = function (id) {
   return this.store[id]
 }
 
-Schemas.prototype.resolveRefs = function (routeSchemas) {
+Schemas.prototype.resolveRefs = function (routeSchemas, dontClearId) {
```
Comment (mcollina) [inline lib/schemas.js]: Can you please add a bit of description of `dontClearId`, and why somebody should set it to `true`?

Comment (Eomm) [reply lib/schemas.js]: That boolean needs because it resolve the shared schema when added without removing the `$id` that is needed by `fastify-plugin`.
If I remove that condition (only) this specific test fails:

https://github.com/fastify/fastify/blob/cf7a0963426ff96fc27f4c92bc443f1ddf8f2311/test/decorator.test.js#L635

because the `$id` would be removed from the object, than the same object reference would be given to children that throw a `FST_ERR_SCH_MISSING_ID` error.
I have tried to clone the object, but I get so many fails..

Only `schemas.js` should set it to true

--- 
Context:

When a shared schema is added, a pair of `$id + JSON with $id` is created

When a JSON schema is resolved by the `validation.js` during the startup, the `JSON with $id` is injected in the right place.
During the injection che `$id` field is deleted because, if a user use two or more time the same shared schema AJV will complain for "multiple equals $id".

If a user add a shared schema with a reference to another shared schema and doesn't use it, the shared shema will not resolved and the code break.

Comment (mcollina) [reply lib/schemas.js]: Can you put some of this explanation in the code itself?

Comment (Eomm) [reply lib/schemas.js]: Done
