### PR TITLE
Extend content type parser

### LINKED ISSUE #2994: catch-all addContentTypeParser doesn't fire if no content-type header in request
## 🐛 Bug Report

Docs state `addContentTypeParser('*', ...` is a catch all to "catch all requests regardless of their content type" but the handler is not called if the request does not have a content-type header.  

Additionally, the catch-all does not fire for application/json because of the built-in parser. That makes sense, but I don't see a `removeContentTypeParser` or way to clear all existing parser.

## To Reproduce

```ts
import fastify, { FastifyReply } from 'fastify';

const port = 8000;
const server = fastify();

server.post('/echo', async (request, reply) => {
  console.log('content-type', request.headers['content-type']);
  console.log('request.body', request.body);
  reply.status(200);
  reply.send(request.body);
});

server.addContentTypeParser('*', (req, payload, done) => {
  console.log('catch all parser entered');
  done();
});
```

```sh
# catch-all parser not hit because content-type not sent 
# (on my machine curl won't send content-type if no data sent.  ymmv)
curl -X POST http://localhost:28588/echo 

# catch-all parser hit and works as expected
curl -H 'content-type:whatever' -X POST -d '{}' http://localhost:28588/echo

# catch-all not hit because built-in json parser handles the request (expected)
curl -X POST -H 'content-type:application/json' -d '{}' http://localhost:28588/echo
```

## Expected behavior

- Catch-all should be called even when there is no content type
- Additionally, it should be possible to remove or clear default parsers
- And the docs should probably be changed to "catch all requests if no other matching parser exists" or something.  I knew what it meant but if taken literally it's not doing what it says

## Your Environment

- *node version*: 12.20.2
- *fastify version*: 3.14.2
- *os*: Mac

I'm trying to always get the request body as a buffer.  #707 was about that and the recommendation was to use a plugin. I couldn't get it to work probably because of what I outlined above.

### PR DESCRIPTION
**Pull request by matthyk**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Closes #2994. This PR adds the 2 methods `resetContentTypeParsers` and `removeContentTypeParser` to the Fastify instance. With `resetContentTypeParsers` all current content type parser can be deleted (including the both built-in content type parsers). This is especially useful if you want to implement a catch-all content type parser that should be called even if the content type is `application/json`. With `removeContentTypeParser` a single or an array of content type parsers can be removed. Both APIs support encapsulation.

```javascript

const app = fastify()

app.removeContentTypeParser('application/json')

app.resetContentTypeParsers()

```

### CODE REVIEW

File: lib/contentTypeParser.js [hunk 1]
```diff
@@ -297,11 +318,33 @@ function hasContentTypeParser (contentType) {
   return this[kContentTypeParser].hasParser(contentType)
 }
 
+function removeContentTypeParser (contentType) {
+  if (this[kState].started) {
+    throw new Error('Cannot call "removeContentTypeParser" when fastify instance is already started!')
+  }
+
+  if (Array.isArray(contentType)) {
+    contentType.forEach((type) => this[kContentTypeParser].remove(type))
```
Comment (mcollina) [inline lib/contentTypeParser.js:327]: Can you please use a for..of loop?

**Review by mcollina — COMMENTED** [review]
good work! Just a nit

File: docs/ContentTypeParser.md [hunk 2]
```diff
@@ -68,6 +72,40 @@ if (!fastify.hasContentTypeParser('application/jsoff')){
...
+  xmlParser(payload, function (err, body) {
+    done(err, body)
+  })
+})
+
+// Removes the both built-in content type parsers so that only the content type parser for text/html is available
+fastiy.removeContentTypeParser(['application/json', 'text/plain'])
+```
+
+#### resetContentTypeParsers
```
Comment (climba03003) [inline docs/ContentTypeParser.md:91]: I think the name can be improved. `Reset` sounds to me reset to some point which mostly reset to default value. 

It would be better if it called `removeAll`.

Comment (delvedor) [reply docs/ContentTypeParser.md:91]: Agreed!

File: lib/contentTypeParser.js (hunk 1 above)
Comment (matthyk) [reply lib/contentTypeParser.js:327]: I will change it later! I used `forEach` because it is also used [here](https://github.com/fastify/fastify/blob/aa58990205ec6923358c5f86a8b0bf55a3f378f0/lib/contentTypeParser.js#L288).

File: docs/ContentTypeParser.md (hunk 2 above)
Comment (matthyk) [reply docs/ContentTypeParser.md:91]: Makes sense to me! I will update the name

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — APPROVED** [review]
Good one!
