### PR TITLE
Do not leak memory if .listen()` is not called

### LINKED ISSUE #4843: Memory Leak: fastify instance kept in memory after calling .close()
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

_No response_

### Node.js version

v18.16.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Description

We are experiencing OOM errors in our tests, both locally (macOS) and in CI (linux).

After some analysis we found that the fastify instances are kept in memory even after `.close()` was called.

We were able to reproduce this in a minimal reproduction, where only the repeated invocation of `Fastify().close()` leads to the allocation of more and more memory.

Screenshot 2023-06-22 at 09 33 19

What looks interesting is the `connectionsCheckingInterval`. This is new in Node.js v18.0.0: https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener. When running the script with Node.js v16.13.0, memory still increases, but not as much and there are no Router/Server instances in memory after the script has finished.

### Steps to Reproduce

```
// memory-test.js
const Fastify = require('fastify')

const initialRss = process.memoryUsage().rss

async function main() {
  for (let i = 0; i < 2000; i += 1) {
    if (i % 100 === 0) {
      global.gc()
      console.log('server', i, process.memoryUsage().rss - initialRss)
    }
    const server = Fastify()
    // eslint-disable-next-line no-await-in-loop
    await server.close()
  }
  await new Promise(resolve => setTimeout(resolve, 1000))
  global.gc()
  debugger
}

main()
```

Run with `node --expose-gc ./memory-test.js` to see logs or `node --inspect-brk --expose-gc ./memory-test.js` to analyse memory allocation.

### Expected Behavior

Fastify instances being freed after calling .close().

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #4843 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: fastify.js [hunk 1]
```diff
@@ -426,10 +426,12 @@ function fastify (options) {
       router.closeRoutes()
 
       hookRunnerApplication('preClose', fastify[kAvvioBoot], fastify, function () {
-        if (fastify[kState].listening) {
-          // No new TCP connections are accepted
-          instance.server.close(done)
+        // No new TCP connections are accepted
+        // we must call close on the server even if we are not listening
+        // otherwise memory will be leaked
```
Comment (jsumners) [inline fastify.js:431]: How about adding a link to the core issue here?

**Review by metcoder95 — APPROVED** [review]
LGTM 👍

**Review by climba03003 — APPROVED** [review]
