### PR TITLE
Run onSend hooks when an encapsulated handler invokes the notFound handler

### LINKED ISSUE #868: "onSend" hook is not being called when handler rejects with {status: 404}
We had a discussion [here](https://github.com/fastify/help/issues/5)

Here's the code to reproduce the issue:

```js
const fastify = require("fastify");
const autocannon = require('autocannon')

let open = 0, count = 0;

function connectPg(fastify) {
  fastify.addHook("preHandler", async function (req, reply) {
    count += 1;
    open += 1
  });

  fastify.addHook("onSend", async (req, res) => {
    open += -1;
  });
}

const legacyRedirects = async (instance, options, next) => {
  connectPg(instance);

  instance.get("/test", async (request, reply) => {
    if (Math.random() < 0.2) return Promise.reject({ status: 404 });
    await new Promise(res => setTimeout(res, Math.random() * 100))
    reply.redirect(301, `/other-route`);
  });
};


const app = fastify({});
app.register(legacyRedirects);
app.listen(9393, err => {
  if (err) throw err;
  console.log(`server listening on ${app.server.address().port}`);

  autocannon({
    url: `http://localhost:${app.server.address().port}/test`,
    connections: 10,
    pipelining: 1,
    duration: 1
  }, (err, res) => {
    console.log(err, res);
    console.log("open/count", `${open}/${count}`)
    app.close();
  })
});
```

Rejecting with `{status: 404}` won't call the "onSend" hook. Any other status I've tested will though.

### PR DESCRIPTION
**Pull request by nwoltman**
If a route is encapsulated, it may have more `onSend` hooks than the *notFound* handler associated with the route. This PR makes sure that if a route invokes the *notFound* handler, all of the route's `onSend` hooks will run.

Fixes #868 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/reply.js [hunk 1]
```diff
@@ -330,8 +330,12 @@ function notFound (reply) {
     return
   }
 
-  reply.context = reply.context._404Context
-  reply.context.handler(reply.request, reply)
+  // Use a copy of the 404 context with the original context's onSend hooks
+  const context = Object.assign({}, reply.context._404Context)
```
Comment (mcollina) [inline lib/reply.js]: Can you use prototypical inheritance here (Object.create..)? So that we avoid a full copy, the context is big and assign is slow.

File: lib/reply.js [hunk 2]
```diff
@@ -330,8 +330,12 @@ function notFound (reply) {
...
+  context.onSend = reply.context.onSend
+  reply.context = context
```
Comment (mcollina) [inline lib/reply.js]: Can you make all this block optional, only if there are onSend hooks?
