### PR TITLE
Fix setting header multiple times and add utility methods (fix #834)

### LINKED ISSUE #834: Cannot set multiple headers of the same name
After this change: https://github.com/fastify/fastify/blame/5c29591ed64618b7428e0ccf8158d84c539e84b1/lib/reply.js#L83-L86

It is impossible to set multiple instances of the same header name. In turn, this makes impossible to send multiple cookies in one request (a totally valid thing to do). Additionally, it also makes the following check always return false -- https://github.com/fastify/fastify-cookie/blob/53378e8d3d7617c8b2ed4d8a16b2b4c0dde7606d/plugin.js#L13-L17

So we need two things:

1. We need to be able to define the same header multiple times
2. We need `getHeader` and `hasHeader` methods on `Reply`

#### Context

* *node version*: 8
* *fastify version*: 1.0.0
* *os*: Mac

### PR DESCRIPTION
**Pull request by jsumners**
This is pushed with a failing test. I have done so because I think that test is wrong, but I want others opinion. The failing test is:

https://github.com/fastify/fastify/blob/6aaa14abbdd317280af68a032a618984d07c38a3/test/stream.test.js#L52-L74

It fails, because now the resulting header is:

```
+++ found
--- wanted
-"application/javascript"
+[
+  "application/octet-stream"
+  "application/javascript"
+]
```

The wrong bit about the test is that the response *should* be `application/octet-stream` since a stream has been sent. However, it could also be wrong that the content type has been set twice.

I feel like we are heading into a mine field with maintaining headers on the `Reply` object ourselves. See https://tools.ietf.org/html/rfc2616#section-4.2:

> Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma. The order in which header fields with the same
   field-name are received is therefore significant to the
   interpretation of the combined field value, and thus a proxy MUST NOT
   change the order of these field values when a message is forwarded.

So is it right to blindly accept multiple values for every header? Or should we be maintaining a list of headers that are allowed to have multiple values?

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nwoltman** [comment]
There really should be 2 methods for setting the header:

+ `setHeader` - Sets the header value. Replaces existing header.
+ `appendHeader` - Sets the header value. Appends to existing header.

Express and Koa both have this pattern.

**Comment by jsumners** [comment]
Core doesn't. See https://github.com/nodejs/node/blob/master/test/parallel/test-http-set-cookies.js

**Comment by nwoltman** [comment]
That's what frameworks are for though. They provide a convenient API for building on top of the underlying system.

**Comment by jsumners** [comment]
Yes, but I agree with the user facing simplicity of `setHeader(name, val)` (or `header(name, val)` in our case). I don't have to ask "did I already set this header and need to set it a second time?" every time I set a header.

**Comment by jsumners** [comment]
I have opted to make a special case of `set-cookie` for now as per [RFC 7320 (§3.2.2)](https://tools.ietf.org/html/rfc7230#section-3.2.2):

> Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
      appears multiple times in a response message and does not use the
      list syntax, violating the above requirements on multiple header
      fields with the same name.  Since it cannot be combined into a
      single field-value, recipients ought to handle "Set-Cookie" as a
      special case while processing header fields.  (See Appendix A.2.3
      of [Kri2001] for details.)

<details>
<summary>Benchmarks</summary>

```
Checking out "master"
Execute "npm run benchmark"

> fastify@1.0.0 benchmark /Users/jsumners/Projects/oss/fastify
> npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 5 -p 10 localhost:3000/"

[0] server listening on 3000
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3.08    9.92    177.88
[1] Req/Sec      31731.2 5116.52 35032
[1] Bytes/Sec    4.68 MB 741 kB  5.22 MB
[1]
[1] 159k requests in 5s, 23.6 MB read
[1] npx autocannon -c 100 -d 5 -p 10 localhost:3000/ exited with code 0
--> Sending SIGTERM to other processes..
[0] node ./examples/simple.js exited with code null
Executed: "npm run benchmark" and exited with code: 0
Execute "npm run benchmark"

> fastify@1.0.0 benchmark /Users/jsumners/Projects/oss/fastify
> npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 5 -p 10 localhost:3000/"

[0] server listening on 3000
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3.04    9.69    229.65
[1] Req/Sec      32049.6 3784.09 34395
[1] Bytes/Sec    4.76 MB 586 kB  5.12 MB
[1]
[1] 160k requests in 5s, 23.9 MB read
[1] npx autocannon -c 100 -d 5 -p 10 localhost:3000/ exited with code 0
--> Sending SIGTERM to other processes..
[0] node ./examples/simple.js exited with code null
Executed: "npm run benchmark" and exited with code: 0
Checking out "oh-the-headers"
Execute "npm run benchmark"

> fastify@1.0.0 benchmark /Users/jsumners/Projects/oss/fastify
> npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 5 -p 10 localhost:3000/"

[0] server listening on 3000
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3.06    9.81    194.32
[1] Req/Sec      31875.2 4227.51 34678
[1] Bytes/Sec    4.73 MB 637 kB  5.17 MB
[1]
[1] 159k requests in 5s, 23.7 MB read
[1] npx autocannon -c 100 -d 5 -p 10 localhost:3000/ exited with code 0
--> Sending SIGTERM to other processes..
[0] node ./examples/simple.js exited with code null
Executed: "npm run benchmark" and exited with code: 0
Execute "npm run benchmark"

> fastify@1.0.0 benchmark /Users/jsumners/Projects/oss/fastify
> npx concurrently -k -s first "node ./examples/simple.js" "npx autocannon -c 100 -d 5 -p 10 localhost:3000/"

[0] server listening on 3000
[1] Running 5s test @ http://localhost:3000/
[1] 100 connections with 10 pipelining factor
[1]
[1] Stat         Avg     Stdev   Max
[1] Latency (ms) 3.03    9.59    263.58
[1] Req/Sec      32254.4 4213.28 34787
[1] Bytes/Sec    4.81 MB 603 kB  5.18 MB
[1]
[1] 161k requests in 5s, 24 MB read
[1] npx autocannon -c 100 -d 5 -p 10 localhost:3000/ exited with code 0
--> Sending SIGTERM to other processes..
[0] node ./examples/simple.js exited with code null
Executed: "npm run benchmark" and exited with code: 0
Back to oh-the-headers 2863f77
```
</details>

**Comment by delvedor** [comment]
Personally I like the proposal of @nwoltman.
This would lead also to a more consistent API:
`getHeader`, `setHeader`, `appendHeader` and alias the actual `header` to `setHeader` (to avoid breaking changes).

File: lib/reply.js [hunk 1]
```diff
@@ -80,8 +80,22 @@ Reply.prototype.send = function (payload) {
   onSendHook(this, payload)
 }
 
+Reply.prototype.getHeader = function (key) {
+  return getHeader(this, key)
+}
+
+Reply.prototype.hasHeader = function (key) {
+  return Object.keys(this._headers).indexOf(key.toLowerCase()) > -1
```
Comment (mcollina) [inline lib/reply.js]: You can use `this._headers[key.toLowerCase()] !== undefined`, it will be faster.

**Comment by mcollina** [comment]
I prefer this logic. It's neat and `Set-Cookie` is a special case anyway.
I think this PR addresses the problem in a simpler way. Supporting `append()` _might_ be very complicated when retrieving data from  `_headers['content-type']` and ohters. Those are property accesses that can be optimized by turbofan. Handling appending data in there will be extremely more complicated.

I'm neutral on the @nwoltman proposal, as I have not see any code yet for that.

**Comment by mcollina** [comment]
https://github.com/fastify/point-of-view/pull/45 also needs this.

File: lib/reply.js (hunk 1 above)
Comment (jsumners) [reply lib/reply.js]: This was when I was still concocting ideas around supporting generic multiple headers. This should definitely be changed.

**Comment by jsumners** [comment]
`hasHeader` has been fixed. Let's get this merged and released so we can continue updating plugins.

**Comment by jsumners** [comment]
Also, `appendHeader` would definitely get tricky. Here's some Mozilla code as proof: https://github.com/bnoordhuis/mozilla-central/blob/master/netwerk/protocol/http/nsHttpHeaderArray.h#L185
